name: Build and Release

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: 'blockcore-vault'

    steps:

    - uses: actions/checkout@master
      name: Checkout

    - uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'

    - name: Variables
      run: |
        echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      shell: bash

    - name: Package Name
      run: |
        echo RELEASE_NAME=${{ env.PROJECT_NAME }}-${{ env.VERSION }}.tgz >> $GITHUB_ENV
      shell: bash

    - name: Install and Build
      run: |
        npm install
        npm run build
    - name: Run Tests
      run: |
        npm run test
    - name: Package
      run: |
        npm pack
    - uses: actions/upload-artifact@v1
      with:
        name: ${{env.PROJECT_NAME}}-preview-${{env.VERSION}}
        path: "${{env.RELEASE_NAME}}"

    - name: Release
      uses: sondreb/action-release@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "${{env.RELEASE_NAME}}"
        draft: true
        prerelease: false
        name: "Blockcore Vault (${{env.VERSION}})"
        tag: ${{env.VERSION}}