name: Build and Release

on: 
  push:
    branches:
      - master
      - main

jobs:
  
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: 'Blockcore.Vault'

    steps:

    - uses: actions/checkout@v1
      name: Checkout

    # - name: Setup Node.js (${{ matrix.node_version }})
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node_version }}

    - name: Variables
      run: |
        echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      shell: bash

    - name: Build
      run: npm run build

    - name: Package Name
      run: |
        echo RELEASE_NAME=${{ env.PROJECT_NAME }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
        echo RELEASE_PATH=${{ env.PROJECT_NAME }}-${{ env.VERSION }} >> $GITHUB_ENV
      shell: bash

    # - name: Package
    #   run: |
    #     echo RELEASE_PATH=./build/ >> $GITHUB_ENV
    #     cd ./build/
    #     tar cvzf ${{env.RELEASE_NAME}} *

    - name: Package (Mac)
      if: matrix.os == 'macos-latest'
      run: zip -r ${{env.RELEASE_NAME}} package.json ./build/

    #- run: mkdir -p path/to/artifact
    #- run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v1
      with:
        name: blockcore-vault
        path: "${{env.RELEASE_PATH}}"

    - name: Release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "${{env.RELEASE_PATH}}"
        draft: true
        prerelease: false
        name: "Blockcore Vault (Release ${{env.VERSION}})"
        tag: ${{env.VERSION}}