name: Build and Release Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Log Variables
      run: |
        echo "action - ${{ github.event.action }}"
        echo "url - ${{ github.event.release.url }}"
        echo "assets_url - ${{ github.event.release.assets_url }}"
        echo "id - ${{ github.event.release.id }}"
        echo "tag_name - ${{ github.event.release.tag_name }}"
        echo "assets - ${{ github.event.assets }}"
        echo "assets[0] - ${{ github.event.assets[0] }}"

    - name: Release Download
      uses: sondreb/action-release-download@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ github.event.release.assets_url }}
        folder: "./artifacts/"

    - name: Display structure of downloaded files
      run: ls -R

    - name: Extract asset
      run: 7z x ./artifacts/*.zip -o~/app

    - name: Display structure of downloaded files
      run: ls -R

    # - name: Unpackage
    #   run: |
    #     tar -xvz -C .
    #   shell: bash

      # - uses: cschleiden/replace-tokens@v1
      #   with:
      #     files: '["Dockerfile"]'
      #   env:
      #     VERSION: ${{ github.event.release.tag_name }}
      #     CHAIN: ${{ matrix.chain }}
      #     NAME: ${{ matrix.name }}
      #     PORTS: ${{ matrix.ports }}
      #     ASSEMBLY: ${{ matrix.assembly }}

      # - name: Build the Docker container image
      #   run: docker build -f "Dockerfile" -t blockcore/node-${{ matrix.name }}:latest -t blockcore/node-${{ matrix.name }}:${{ github.event.release.tag_name }} --label "unstable=true" "."

      # - name: Login and Push to Docker Registry
      #   run: |
      #     docker login -u "sondreb" -p "${{secrets.DockerHubSecret}}"
      #     docker push --all-tags blockcore/node-${{ matrix.name }}
